### ISSUE TITLE
2.0.x is not able to create targets automatically

### ISSUE THREAD

**Issue by nostalgiaz** [harness/ff-proxy#324]
Moving from the 1.0.4 to the 2.0.x (both 2.0.0 and 2.0.1) I have some problems with creating targets automatically when a new user asks for a feature flag. The proxy reply telling that no feature flags are enabled. The /client/auth request returns with status code 200.
Rolling back to the 1.0.4 or bypassing the ff-proxy everything works like a charm.

If i can provide you something more, just ask!

**Comment by ilpianista** [comment]
Maybe related to #285?

**Comment by jcox250** [comment]
Hi @ilpianista 

I'm really sorry for the delayed response, I missed this issue and it's only just come to my attention. 

> Moving from the 1.0.4 to the 2.0.x (both 2.0.0 and 2.0.1) I have some problems with creating targets automatically when a new user asks for a feature flag. The proxy reply telling that no feature flags are enabled. The /client/auth request returns with status code 200. Rolling back to the 1.0.4 or bypassing the ff-proxy everything works like a charm.
> 
> If i can provide you something more, just ask!

Just to make sure I'm understanding the question, when you say 2.0.x is not able to create targets automatically do you mean if you use 2.0.x you don't see the targets appear in the UI? But when you use 1.x you do see targets appear in the UI? 

If what I'm asking above is correct then yes it would be related to this change you mentioned. In v2 of the Proxy we made the decision to not forward targets on to Harness Saas by default, the Proxy still creates them and adds them to its redis cache but because they aren't forwarded on to Harness Saas you won't see them in the UI. If you want to see the Targets in the UI you can enable this functionality by setting the environment variable `FORWARD_TARGETS=true`

> Maybe related to #285?

However I've just realised we only added support for forwarding targets on to the Primary Proxy in V2 and not the read replicas. If you're running v2 as a single Primary the same way you would with v1 then it should all work ok as long as the `FORWARD_TARGETS=true` environment variable is set. However if you're planning on running the V2 Proxy in [HA Mode](https://developer.harness.io/docs/feature-flags/use-ff/relay-proxy/relay_proxy_v2/#ha-mode) then we'll need to do some work so the replicas support forwarding the targets on.

**Comment by ilpianista** [comment]
Sorry for the late reply, setting `FORWARD_TARGETS=true` solved my issue. Thanks!

**Comment by jcox250** [comment]
No worries, glad that helped resolve the issue!
